### PR TITLE
Remove vendor dir

### PR DESCRIPTION
**Pull request by cblecker**
### What type of PR is this? 
cleanup

### What this PR does / why we need it:
Removes the unused vendor dir

### Which issue(s) this PR fixes(can be a reference to existing issue or jira/bz):

_Fixes #_

### Pre-checks:
- [ ] manually tested latest changes against crc/k8s
- [ ] run the `make coverage` command to generate new calculated coverage

### CODE REVIEW

**Comment by georgettica** [comment]
it is used I think.
are we moving away from the vendoring?

**Comment by fahlmant** [comment]
Vendoring is no longer needed with go modules. We've moved away from it in all other repos we manage

**Comment by georgettica** [comment]
When was this announced?
/lgtm
/approve
Then

**Comment by fahlmant** [comment]
@georgettica This happened when go 1.16 was released in Feb 2021

**Pull request merged**
