### PR TITLE
Make regions configurable

### PR DESCRIPTION
**Pull request by NautiluX**
### What type of PR is this? 
_feature_

### Which issue(s) this PR fixes(can be a reference to existing issue or jira/bz):

_Fixes OSD-3545_

### Pre-checks:
- [x] manually tested latest changes against crc/k8s
- [ ] run the `make coverage` command to generate new calculated coverage

### CODE REVIEW

**Comment by NautiluX** [comment]
/hold
pending manual tests

**Comment by NautiluX** [comment]
also need to update config maps in deployments

**Comment by NautiluX** [comment]
manual tests done, config changes pending

**Comment by NautiluX** [comment]
/hold cancel
config present on clusters

**Comment by georgettica** [comment]
maybe add a section in the https://github.com/openshift/gcp-project-operator/blob/master/docs/gcpconfig.md for the configmap change

**Review by georgettica — APPROVED** [review]

**Pull request merged**
