### PR TITLE
OSD-6853: CatalogSource by digest

### PR DESCRIPTION
**Pull request by jharrington22**
Depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17948

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/lgtm

Needs a gcp-project-operator approver

Continue to /hold for deps

**Comment by cblecker** [comment]
This is a well-tested change and is required to unblock moving this operator to digest builds. Manually approving.

**Comment by 2uasimojo** [comment]
/hold cancel

Deps are in

**Pull request merged**
