### PR TITLE
Update run command

### PR DESCRIPTION
**Pull request by drpaneas**
- Flag --local has been deprecated, use 'run local' instead
 - Flag --namespace is deprecated; use --watch-namespace instead.

### What type of PR is this? 
_docs_

### What this PR does / why we need it:

because we updated to the new operator-sdk version.

### Pre-checks:
- [x] manually tested latest changes against crc/k8s
- [x] run the `make coverage` command to generate new calculated coverage

### CODE REVIEW

**Comment by georgettica** [comment]
this is version dependant. maybe put a note that this is in the newer versions

**Comment by drpaneas** [comment]
> this is version dependant. maybe put a note that this is in the newer versions

done, thx

**Comment by georgettica** [comment]
once more :)

**Pull request merged**
