### PR TITLE
refactor: crd v1 upgrade, remove crd v1beta1 ruins

### PR DESCRIPTION
**Pull request by boranx**
### What type of PR is this? 
Refactor

### What this PR does / why we need it:
crd v1beta1 will be deprecated soon

### Which issue(s) this PR fixes(can be a reference to existing issue or jira/bz):

Fix: https://issues.redhat.com/browse/OSD-7596

### Special notes for your reviewer:
This has been tested on stage

### Is it a breaking change or backward compatible?
breaking change

### Pre-checks:
- [x] manually tested latest changes against crc/k8s
- [ ] run the `make coverage` command to generate new calculated coverage

### CODE REVIEW

**Comment by boranx** [comment]
@2uasimojo @drpaneas since the previous [PR](https://github.com/openshift/gcp-project-operator/pull/159) merged accidentally (while I was trying to add hold label) and we reverted it back, would it be possible to review also this PR?

**Comment by boranx** [comment]
the only delta is the `README.md` where we're explaining applying of the crds (also included crd naming changes)

**Comment by 2uasimojo** [comment]
Yup, still

/lgtm

**Comment by rafael-azevedo** [comment]
@boranx looks good to me I will merge tomorrow AM eastern time when you are on just to be safe

**Pull request merged**
