### PR TITLE
ProjectClaim controller creates ProjectReference

### PR DESCRIPTION
**Pull request by NautiluX**

### CODE REVIEW

**Comment by rafael-azevedo** [comment]
The only thing that is confusing is the naming convention of the "ProjectClaimReconciler" since there is already another reconcile object. Though I am not sure on a good name.

**Comment by rafael-azevedo** [comment]
Have you also tested this workflow locally  ?

**Comment by NautiluX** [comment]
Thanks for your review @rafael-azevedo, I'll try to come up with a better name. As discussed I tested the workflow locally and will have another look to make sure no outdated objects are used.

**Pull request merged**
