### PR TITLE
[SDE-3226] Add shared vpc access spec field

### PR DESCRIPTION
**Pull request by zmird-r**
### What type of PR is this? 
Feature

### What this PR does / why we need it:
Adds necessary roles to provision GCP Shared VPCs

### Ticket
[SDE-3226](https://issues.redhat.com/browse/SDE-3226)

### CODE REVIEW

**Comment by zmird-r** [comment]
Updated boilerplate since the tests kept failing.

**Review by rafael-azevedo — APPROVED** [review]
/lgtm

**Pull request merged**
