### PR TITLE
fix(secret): make deletion work

### PR DESCRIPTION
**Pull request by georgettica**

### CODE REVIEW

**Comment by georgettica** [comment]
/hold
still in testing, but at least we can see tests passing

**Comment by georgettica** [comment]
this works, but tests are failing :(

**Comment by georgettica** [comment]
/unhold
tests look good (now on CCS aswell)

**Comment by georgettica** [comment]
now that I have go 1.14, this can be merged.. @NautiluX ?

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Pull request merged**
