### PR TITLE
refactor: crd v1 upgrade, remove crd v1beta1 ruins

### PR DESCRIPTION
**Pull request by boranx**
### What type of PR is this? 
Refactor

### What this PR does / why we need it:
crd v1beta1 will be deprecated soon

### Which issue(s) this PR fixes(can be a reference to existing issue or jira/bz):
Fix: https://issues.redhat.com/browse/OSD-7596

### Special notes for your reviewer:
the procedure documented at https://issues.redhat.com/browse/OSD-7604 has been followed.

### Is it a breaking change or backward compatible?
breaking change

### Pre-checks:
- [ ] manually tested latest changes against crc/k8s
- [ ] run the `make coverage` command to generate new calculated coverage

### CODE REVIEW

**Review by 2uasimojo — COMMENTED** [review]
✓ BP update is good (latest)
✓ CRDs install cleanly
✓ `oc explain` works on both
✓ Old CRDs are removed.

/lgtm

**Comment by boranx** [comment]
this has been tested against staging by applying the v1 crds

**Pull request merged**
