### PR TITLE
Update Owners file

### PR DESCRIPTION
**Pull request by sam-nguyen7**
### What type of PR is this? 
_(bug/feature/cleanup/docs/design/test/chore/refactor..)_

### Which issue(s) this PR fixes(can be a reference to existing issue or jira/bz):

_Fixes #_

### Pre-checks:
- [ ] manually tested latest changes against crc/k8s
- [ ] run the `make coverage` command to generate new calculated coverage

### CODE REVIEW

**Comment by RiRa12621** [comment]
@sam-nguyen7 can you incorporate https://github.com/openshift/gcp-project-operator/pull/112
then we only need one change and no one needs to rebase?

**Comment by sam-nguyen7** [comment]
@RiRa12621 done

**Pull request merged**
